repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0  # Use the appropriate version
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*
