title = "Gaspard Blogs"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "archi"
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Gaspard's blog"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/samuel-casin-324a26209/"

###github_ssh_private_key=
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,512765DD795F7EBF

JsRahDl3foQAij6BMLGyg+WXBTNkIc65MKJ2DA134bmV9YyTT+UAAt9sBIgNNXxp
gapx4XO/LPwd6Xorq0Fhj5TsiW124gU/3uLPqlfqckX3GLRBj5z0Ad2nTVyRJghH
9Yu4i3YiW8E5WQlLAlbOg2/l4ioUoXO3R4v8hxvxOPSvSdgPMnSE7CE67iIAoNuy
wtMs8HVWZXJNFj0W/qerPL3M8yu8xq2lQavzL0+ePSlURVSQ8ENR34cTpMCM/XwH
KSBNUmIgWVZPytgRKjSs5mPV65LSCvuvt61YZli3UdNeE5cbIIRWbUEBebdjbjHk
pw7iCDELiITGrUBpaeFMqfprl75jmkRsvIimgRvVVOmuIsY8Pq8m6kxdEjgvreuh
YDcHFjkoM0UzOdCidt1WHRcz+XRrBZ+k4fUfiLOCzxU1hklGLV7WbW9qh30tA8KE
WNx7nu/0T5IxQykiVS8PleAbbgtptPHGCXUmkMyup7/2G5Fgkvjrexxki0ZbbTiq
zvOlQjanrduoVCKfRVCUVnSVOaU156w2+5kHBlqT+gThedmBdhOET3ZHeoomETfr
27JH9zfTIx0tWotDmAM1uvhKDQRqpeu0mPqB4Lpa3guvfabvJPl75HHOU4rqhxAl
RRaS7sccxGQbGLElnW+KavdxEitJonHheOT1BTmgk6MlPf1dmu7uxAI5EPkY64bn
WRhmKN5bhm3+hdjicPMERL87w3/qlGVhtV3vZuFo8lj74o65YMtIFsWEmoklISxM
WsyC7SRZp0hhz/5n/NJ7I/Ue+c6CptgQZ9uIPGNTnmn2miUuZLwRngkZvugcXrgc
euZrjgqmKZDI7aJ+eP1LqFytlROewLIcMaDvZ3LgSCm/F4Nfz9rkV5iqT54Ev29a
x2+rpEGFtfPrNCNkTaQsxgC5x97q81LgCYwt3YmlA1U6aN006BzrcHUqUMwvpYCD
gxl3RTzHdXumpG1TqoiuSBTDT4EmlcrOhfKL3POmseyFJ2TTGK1CHOq0WX+aa6cA
fySXzH7QlP5MNkD/m/kd0j32Hx3p6m1ajxbnm8dPyH/7OkcGbuWXZUFsBXC+HN1S
yCNjmUizaF846/XbGW9OzMqqeSwveWIUc0BOJA8LzXnBL7jE8iL7rTHF9ItV0q2X
040R+73iKmIsXVPOopsFO1BAA2amRarV4SL6t7YTJU6WXqGNkipKYiR+p35NCXNK
GYkPOIVBvtBw/3GDDQYAM/uNPEJ9DUOJ+m4DYooiIrFUdNmxop7YN/rKMDqIJz3m
nKKs0afYXDkNWRcYuuzQIynsVt51nLBu72FC0f6owO4lVg2OnR1SaC5e4Od4Wr6r
vx5a+Z8iLLMwQhdBHx9IRc+guQC6JWQtFlQ75zuSIhJLJqQaTcynu4fBxecYRaRp
ByLZ/XTn3zI5A0oL9PQu4LCMOPSBbptPjW4FjTzG9s5jeX/F0sU7vwaqVwWeoozL
8Q3eMsw4ddb8B5idAnx+J/wXq3X6uWu+jpCh/Gd1yNVxCl5qtk8UbRfaj7myCb4T
aRfRLMcZcXW/MxGcgy26G3AGoKqA/CZOG0oSNHSnczBCRvMqua/sHx11x44qKqGN
-----END RSA PRIVATE KEY-----
###


